// Generated by tools/make_airports.py — do not edit by hand.
//
// Major European airports from OurAirports (public domain): every
// large_airport, then the medium_airports with an IATA code and
// scheduled service, within lon -25..45 / lat 34..72,
// positions quantized to 1/400 degree fixed point. Runway
// headings (degrees mod 180, parallels merged) index into one flat
// byte array. The arrays are const, so they live in flash
// (memory-mapped on the ESP32-S3), not RAM.

#pragma once

#include <stdint.h>

namespace airportdata {

// Degrees per fixed-point unit: lat = kAirports[i].lat * kDegPerUnit.
constexpr float kDegPerUnit = 0.0025f;

struct Airport {
  int16_t lat;        // Fixed-point 1/400 degree.
  int16_t lon;
  char iata[4];       // IATA code, NUL terminated.
  uint16_t rwyStart;  // First entry in kRunwayHeadings.
  uint8_t rwyCount;   // Number of runway strips.
};

// Large airports first (always drawn), then medium (zoomed in only).
constexpr int kLargeCount = 300;
constexpr int kCount = 595;

constexpr Airport kAirports[] = {
    {14731, 3125, "AAE", 0, 2},  // Annaba Rabah Bitat Airport
    {22838, 3940, "AAL", 2, 1},  // Aalborg Airport
    {22521, 4247, "AAR", 3, 1},  // Aarhus Airport
    {22881, -879, "ABZ", 4, 1},  // Aberdeen International Airport
    {14793, 14112, "ADA", 5, 1},  // Adana Şakirpaşa Airport
    {15317, 10863, "ADB", 6, 1},  // Adnan Menderes International Airport
    {17380, 15983, "AER", 7, 2},  // Sochi International Airport
    {25024, 2444, "AES", 9, 1},  // Ålesund Airport
    {26263, -7229, "AEY", 10, 1},  // Akureyri International Airport
    {14670, -1800, "AGP", 11, 2},  // Málaga-Costa del Sol Airport
    {15313, -223, "ALC", 13, 1},  // Alicante-Elche Miguel Hernández Airport
    {14678, 1286, "ALG", 14, 2},  // Houari Boumediene Airport
    {14473, 14891, "ALP", 16, 1},  // Aleppo International Airport
    {20923, 1906, "AMS", 17, 4},  // Amsterdam Airport Schiphol
    {15925, 12208, "AOE", 21, 1},  // Hasan Polatkan Airport
    {23859, 7172, "ARN", 22, 2},  // Stockholm-Arlanda Airport
    {15508, 14198, "ASR", 24, 1},  // Kayseri Erkilet International Airport
    {15175, 9578, "ATH", 25, 1},  // Athens Eleftherios Venizelos International Airport
    {14759, 12320, "AYT", 26, 1},  // Antalya International Airport
    {17801, 10441, "BBU", 27, 1},  // Bucharest Băneasa Aurel Vlaicu International Airport
    {18609, 10764, "BCM", 28, 1},  // Bacău George Enescu International  Airport
    {16519, 831, "BCN", 29, 2},  // Josep Tarradellas Barcelona-El Prat Airport
    {16263, 7179, "BDS", 31, 2},  // Brindisi Airport
    {17927, 8124, "BEG", 33, 1},  // Belgrade Nikola Tesla Airport
    {20945, 5401, "BER", 34, 1},  // Berlin Brandenburg Airport
    {19379, -1767, "BES", 35, 1},  // Brest Bretagne airport
    {21863, -2486, "BFS", 36, 2},  // Belfast International Airport
    {24117, 2087, "BGO", 38, 1},  // Bergen Airport, Flesland
    {18268, 3884, "BGY", 39, 2},  // Il Caravaggio International Airport
    {20982, -699, "BHX", 41, 1},  // Birmingham Airport
    {17021, 3793, "BIA", 42, 1},  // Bastia-Poretta International airport
    {17320, -1164, "BIO", 43, 2},  // Bilbao Airport
    {14685, 2028, "BJA", 45, 1},  // Soummam–Abane Ramdane Airport
    {14900, 11066, "BJV", 46, 1},  // Milas Bodrum International Airport
    {14301, 2523, "BLJ", 47, 1},  // Batna Mostefa Ben Boulaid Airport
    {22296, 3663, "BLL", 48, 1},  // Billund Airport
    {17814, 4515, "BLQ", 49, 1},  // Bologna Guglielmo Marconi Airport
    {17977, 6919, "BNX", 50, 1},  // Banja Luka International Airport
    {17931, -286, "BOD", 51, 2},  // Bordeaux–Mérignac Airport
    {17028, 11006, "BOJ", 53, 1},  // Burgas Airport
    {26908, 5746, "BOO", 54, 1},  // Bodø Airport
    {20843, 9559, "BQT", 55, 1},  // Brest International Airport
    {21219, 3516, "BRE", 56, 2},  // Bremen Airport
    {16456, 6704, "BRI", 58, 1},  // Bari Karol Wojtyła International Airport
    {20553, -1087, "BRS", 59, 1},  // Bristol Airport
    {20361, 1794, "BRU", 60, 2},  // Brussels Airport
    {13917, 2296, "BSK", 62, 1},  // Biskra - Mohamed Khider Airport
    {19040, 3008, "BSL", 63, 2},  // EuroAirport Basel–Mulhouse–Freiburg
    {19268, 6885, "BTS", 65, 2},  // M. R. Štefánik Airport
    {18972, 7705, "BUD", 67, 1},  // Budapest Liszt Ferenc International Airport
    {16644, 16640, "BUS", 68, 1},  // Alexander Kartveli Batumi International Airport
    {19782, 845, "BVA", 69, 2},  // Beauvais-Tillé airport
    {15701, 3622, "CAG", 71, 1},  // Cagliari Elmas Airport
    {19604, 1022, "CDG", 72, 1},  // Charles de Gaulle International Airport
    {18315, 1268, "CFE", 73, 2},  // Clermont-Ferrand Auvergne airport
    {14487, 536, "CFK", 75, 2},  // Chlef Aboubakr Belkaid International Airport
    {15841, 7965, "CFU", 77, 1},  // Corfu Ioannis Kapodistrias International Airport
    {20346, 2857, "CGN", 78, 2},  // Cologne Bonn Airport
    {14212, 9660, "CHQ", 80, 1},  // Chania International Airport
    {16720, 5038, "CIA", 81, 1},  // Ciampino–G. B. Pastine International Airport
    {18714, 9474, "CLJ", 82, 1},  // Avram Iancu Cluj International Airport
    {17745, 11395, "CND", 83, 1},  // Mihail Kogălniceanu International Airport
    {14757, 14028, "COV", 84, 1},  // Çukurova International Airport
    {22247, 5062, "CPH", 85, 2},  // Copenhagen Kastrup Airport
    {17727, 9555, "CRA", 87, 1},  // Craiova International Airport
    {20185, 1784, "CRL", 88, 1},  // Brussels South Charleroi Airport
    {14987, 6027, "CTA", 89, 1},  // Catania-Fontanarossa Airport
    {20559, -1337, "CWL", 90, 1},  // Cardiff International Airport
    {14510, 2648, "CZL", 91, 2},  // Mohamed Boudiaf International Airport
    {17025, 7306, "DBV", 93, 1},  // Dubrovnik Ruđer Bošković Airport
    {18996, 8647, "DEB", 94, 1},  // Debrecen International Airport
    {14685, 11517, "DLM", 95, 1},  // Dalaman International Airport
    {22164, 15163, "DME", 96, 1},  // Domodedovo International Airport
    {20454, 5507, "DRS", 97, 1},  // Dresden Airport
    {20607, 3045, "DTM", 98, 1},  // Dortmund Airport
    {21371, -2505, "DUB", 99, 2},  // Dublin Airport
    {20516, 2707, "DUS", 101, 1},  // Düsseldorf Airport
    {14494, 17579, "EBL", 102, 1},  // Erbil International Airport
    {14061, 13403, "ECN", 103, 1},  // Ercan International Airport
    {22380, -1349, "EDI", 104, 1},  // Edinburgh Airport
    {15821, 10804, "EDO", 105, 1},  // Balıkesir Koca Seyit Airport
    {20580, 2150, "EIN", 106, 1},  // Eindhoven Airport
    {21132, -531, "EMA", 107, 1},  // East Midlands Airport
    {20391, 4384, "ERF", 108, 1},  // Erfurt-Weimar Airport
    {16051, 13198, "ESB", 109, 1},  // Esenboğa International Airport
    {27397, 6671, "EVE", 110, 1},  // Harstad/Narvik Airport
    {16060, 17759, "EVN", 111, 1},  // Zvartnots International Airport
    {24825, -2910, "FAE", 112, 1},  // Vágar Airport
    {14806, -3188, "FAO", 113, 1},  // Faro - Gago Coutinho International Airport
    {16722, 4901, "FCO", 114, 2},  // Rome–Fiumicino Leonardo da Vinci International Airport
    {19069, 3805, "FDH", 116, 1},  // Bodensee Airport Friedrichshafen
    {19512, 3232, "FKB", 117, 1},  // Karlsruhe Baden-Baden Airport
    {17523, 4481, "FLR", 118, 1},  // Florence Airport, Peretola
    {19195, 4095, "FMM", 119, 1},  // Memmingen Allgau Airport
    {20854, 3075, "FMO", 120, 1},  // Münster Osnabrück Airport
    {20011, 3423, "FRA", 121, 2},  // Frankfurt Main Airport
    {16601, 3639, "FSC", 123, 1},  // Figari Sud-Corse Airport
    {21751, 7386, "GDN", 124, 1},  // Gdańsk Lech Wałęsa Airport
    {18282, 10209, "GHV", 125, 1},  // Brașov-Ghimbav International Airport
    {14461, -2140, "GIB", 126, 1},  // Gibraltar Airport
    {14718, 2349, "GJL", 127, 1},  // Jijel Ferhat Abbas Airport
    {22349, -1773, "GLA", 128, 1},  // Glasgow Airport
    {14978, 15558, "GNY", 129, 1},  // Şanlıurfa GAP Airport
    {17765, 3536, "GOA", 130, 1},  // Genoa Cristoforo Colombo Airport
    {22491, 17514, "GOJ", 131, 3},  // Nizhny Novgorod / Strigino International Airport
    {23065, 4912, "GOT", 134, 1},  // Göteborg Landvetter Airport
    {16762, 1105, "GRO", 135, 1},  // Girona-Costa Brava Airport
    {21248, 2631, "GRQ", 136, 1},  // Groningen Airport Eelde
    {18796, 6176, "GRZ", 137, 1},  // Graz Airport
    {18495, 2444, "GVA", 138, 1},  // Geneva International Airport
    {14779, 14991, "GZT", 139, 1},  // Gaziantep Oğuzeli International Airport
    {20984, 3874, "HAJ", 140, 1},  // Hannover Airport
    {21452, 3995, "HAM", 141, 2},  // Hamburg Helmut Schmidt Airport
    {24127, 9985, "HEL", 143, 2},  // Helsinki Vantaa Airport
    {14136, 10072, "HER", 145, 2},  // Heraklion International Nikos Kazantzakis Airport
    {19979, 2905, "HHN", 147, 1},  // Frankfurt-Hahn Airport
    {23024, 16063, "IAR", 148, 1},  // Golden Ring Yaroslavl International Airport
    {18872, 11049, "IAS", 149, 1},  // Iaşi International Airport
    {15549, 549, "IBZ", 150, 1},  // Ibiza Airport
    {17335, 8742, "INI", 151, 1},  // Niš Constantine the Great Airport
    {18904, 4538, "INN", 152, 1},  // Innsbruck Airport
    {21633, -1850, "IOM", 153, 2},  // Isle of Man Airport
    {16389, 11529, "ISL", 155, 1},  // İstanbul Atatürk Airport
    {16510, 11493, "IST", 156, 1},  // İstanbul Airport
    {27443, 10962, "IVL", 157, 2},  // Ivalo Airport
    {19579, 5771, "JCL", 159, 1},  // České Budějovice South Bohemian Airport
    {14560, 10191, "JTR", 160, 1},  // Santorini International Airport
    {25594, -9042, "KEF", 161, 2},  // Keflavik International Airport
    {21957, 8239, "KGD", 163, 1},  // Khrabrovo Airport
    {14718, 10836, "KGS", 164, 1},  // Kos International Airport "Ippokratis"
    {14188, 17740, "KIK", 165, 2},  // Kirkuk International Airport
    {18657, 5735, "KLU", 167, 1},  // Klagenfurt Airport
    {20081, 5166, "KLV", 168, 1},  // Karlovy Vary Airport
    {20031, 7914, "KRK", 169, 1},  // Kraków John Paul II International Airport
    {27129, 8135, "KRN", 170, 1},  // Kiruna Airport
    {18014, 15670, "KRR", 171, 1},  // Krasnodar Pashkovsky International Airport
    {23282, 3234, "KRS", 172, 1},  // Kristiansand Airport
    {20567, 3757, "KSF", 173, 1},  // Kassel Airport
    {27080, 9939, "KTT", 174, 1},  // Kittilä International Airport
    {20190, 7632, "KTW", 175, 1},  // Katowice Wojciech Korfanty International Airport
    {21986, 9634, "KUN", 176, 1},  // Kaunas International Airport
    {25203, 11119, "KUO", 177, 1},  // Kuopio Airport
    {16871, 16994, "KUT", 178, 1},  // David the Builder Kutaisi International Airport
    {16365, 9848, "KVA", 179, 1},  // Kavala Alexander the Great International Airport
    {15192, 13025, "KYA", 180, 1},  // Konya Airport
    {21546, -664, "LBA", 181, 1},  // Leeds Bradford Airport
    {19585, 975, "LBG", 182, 3},  // Paris-Le Bourget International Airport
    {13950, 13450, "LCA", 185, 1},  // Larnaca International Airport
    {20689, 7759, "LCJ", 186, 1},  // Łódź Władysław Reymont Airport
    {23920, 12105, "LED", 187, 1},  // Pulkovo Airport
    {20568, 4893, "LEJ", 188, 1},  // Leipzig/Halle Airport
    {20459, -74, "LGW", 189, 1},  // London Gatwick Airport
    {20588, -184, "LHR", 190, 1},  // London Heathrow Airport
    {20227, 1241, "LIL", 191, 2},  // Lille Airport
    {18178, 3711, "LIN", 193, 1},  // Milano Linate Airport
    {15513, -3654, "LIS", 194, 1},  // Lisbon Humberto Delgado Airport
    {18489, 5783, "LJU", 195, 1},  // Ljubljana Jože Pučnik Airport
    {26218, 8849, "LLA", 196, 1},  // Luleå Airport
    {19294, 5675, "LNZ", 197, 2},  // Linz-Hörsching Airport
    {23362, 6274, "LPI", 199, 1},  // Linköping City Airport
    {21334, -1140, "LPL", 200, 1},  // Liverpool John Lennon Airport
    {24418, 11258, "LPP", 201, 1},  // Lappeenranta Airport
    {22607, 8439, "LPX", 202, 1},  // Liepāja International Airport
    {20750, -147, "LTN", 203, 1},  // London Luton Airport
    {19851, 2485, "LUX", 204, 1},  // Luxembourg-Findel International Airport
    {20496, 9085, "LUZ", 205, 1},  // Lublin Airport
    {16300, 17544, "LWN", 206, 1},  // Shirak International Airport
    {19925, 9582, "LWO", 207, 1},  // Lviv International Airport
    {18290, 2036, "LYS", 208, 1},  // Lyon Saint-Exupéry Airport
    {16197, -1429, "MAD", 209, 2},  // Adolfo Suárez Madrid–Barajas Airport
    {15945, 1687, "MAH", 211, 1},  // Menorca Airport
    {21340, -912, "MAN", 212, 1},  // Manchester Airport
    {14338, 5797, "MLA", 213, 2},  // Malta International Airport
    {27513, 13100, "MMK", 215, 1},  // Emperor Nicholas II Murmansk Airport
    {22214, 5351, "MMX", 216, 2},  // Malmö Sturup Airport
    {17430, 1585, "MPL", 218, 1},  // Montpellier-Méditerranée Airport
    {17375, 2085, "MRS", 219, 1},  // Marseille Provence Airport
    {17690, 17233, "MRV", 220, 1},  // Mineralnye Vody Airport
    {21555, 11216, "MSQ", 221, 1},  // Minsk National Airport
    {20364, 2308, "MST", 222, 1},  // Maastricht Aachen Airport
    {19342, 4714, "MUC", 223, 1},  // Munich Airport
    {18252, 3491, "MXP", 224, 1},  // Milan Malpensa International Airport
    {16354, 5716, "NAP", 225, 1},  // Naples International Airport
    {15509, 13814, "NAV", 226, 1},  // Nevşehir Kapadokya Airport
    {17463, 2886, "NCE", 227, 1},  // Nice-Côte d'Azur Airport
    {22015, -676, "NCL", 228, 1},  // Newcastle International Airport
    {13996, -1211, "NDR", 229, 1},  // Nador Al Aaroui International Airport
    {21564, -3527, "NOC", 230, 1},  // Ireland West Airport Knock
    {20641, 2456, "NRN", 231, 1},  // Weeze (Niederrhein) Airport
    {19799, 4431, "NUE", 232, 1},  // Nuremberg Airport
    {23516, 6765, "NYO", 233, 2},  // Stockholm Skavsta Airport
    {22190, 4131, "ODE", 235, 2},  // Odense Hans Christian Andersen Airport
    {18571, 12269, "ODS", 237, 2},  // Odesa International Airport
    {16472, 8297, "OHD", 239, 1},  // Ohrid St. Paul the Apostle Airport
    {16360, 3807, "OLB", 240, 1},  // Olbia Costa Smeralda Airport
    {17313, 7138, "OMO", 241, 1},  // Mostar International Airport
    {18810, 8761, "OMR", 242, 1},  // Oradea International Airport
    {16499, -3473, "OPO", 243, 1},  // Francisco de Sá Carneiro Airport
    {20737, -3396, "ORK", 244, 2},  // Cork International Airport
    {14248, -249, "ORN", 246, 1},  // Oran Es-Sénia (Ahmed Ben Bella) International Airport
    {19492, 944, "ORY", 247, 3},  // Paris-Orly Airport
    {24078, 4440, "OSL", 250, 1},  // Oslo-Gardermoen International Airport
    {14522, 17259, "OSM", 251, 1},  // Mosul International Airport
    {19879, 7244, "OSR", 252, 1},  // Leoš Janáček Airport Ostrava
    {20480, 1150, "OST", 253, 1},  // Ostend-Bruges International Airport
    {17829, 10441, "OTP", 254, 1},  // Bucharest Henri Coandă International Airport
    {13916, -770, "OUD", 255, 2},  // Oujda Angads Airport
    {25972, 10142, "OUL", 257, 1},  // Oulu Airport
    {17425, -2414, "OVD", 258, 1},  // Asturias Airport
    {19147, 14126, "OZH", 259, 1},  // Zaporizhzhia International Airport
    {20645, 3447, "PAD", 260, 1},  // Paderborn Lippstadt Airport
    {16827, 9940, "PDV", 261, 1},  // Plovdiv International Airport
    {20006, 6296, "PED", 262, 1},  // Pardubice Airport
    {17238, 5005, "PEG", 263, 1},  // Perugia San Francesco d'Assisi – Umbria International Airport
    {18396, 7297, "PEV", 264, 1},  // Pécs-Pogány International Airport
    {13887, 12994, "PFO", 265, 1},  // Paphos International Airport
    {22201, -1831, "PIK", 266, 2},  // Glasgow Prestwick Airport
    {22389, 8438, "PLQ", 268, 1},  // Palanga International Airport
    {15821, 1096, "PMI", 269, 1},  // Palma de Mallorca Airport
    {15270, 5236, "PMO", 270, 2},  // Falcone–Borsellino Airport
    {20969, 6729, "POZ", 272, 1},  // Poznań-Ławica Airport
    {20040, 5704, "PRG", 273, 2},  // Václav Havel Airport Prague
    {17029, 8414, "PRN", 275, 1},  // Priština Adem Jashari International Airport
    {17474, 4157, "PSA", 276, 1},  // Pisa International Airport
    {16972, 5673, "PSR", 277, 1},  // Abruzzo Airport
    {17957, 5569, "PUY", 278, 1},  // Pula Airport
    {13621, -2701, "RBA", 279, 1},  // Rabat-Salé Airport
    {16459, 467, "REU", 280, 1},  // Reus Airport
    {14562, 11234, "RHO", 281, 1},  // Rhodes International Airport "Diagoras"
    {22768, 9588, "RIX", 282, 1},  // Riga International Airport
    {18087, 5828, "RJK", 283, 1},  // Rijeka Airport
    {17608, 5045, "RMI", 284, 1},  // Federico Fellini International Airport
    {18771, 11573, "RMO", 285, 1},  // Chişinău International Airport
    {15121, -450, "RMU", 286, 1},  // Region of Murcia International Airport
    {18998, 15970, "ROV", 287, 1},  // Platov International Airport
    {20783, 1775, "RTM", 288, 1},  // Rotterdam The Hague Airport
    {26625, 10332, "RVN", 289, 1},  // Rovaniemi Airport
    {20044, 8810, "RZE", 290, 2},  // Rzeszów-Jasionka Airport
    {16472, 16340, "RZV", 292, 1},  // Rize–Artvin Airport
    {16359, 11724, "SAW", 293, 1},  // Istanbul Sabiha Gökçen International Airport
    {18314, 9635, "SBZ", 294, 1},  // Sibiu International Airport
    {17159, -3366, "SCQ", 295, 1},  // Santiago-Rosalía de Castro Airport
    {24466, 5133, "SCR", 296, 1},  // Scandinavian Mountains Airport
    {19075, 10542, "SCV", 297, 1},  // Suceava Ștefan cel Mare International Airport
    {18021, 13590, "SIP", 298, 1},  // Simferopol International Airport
    {17530, 7333, "SJJ", 299, 1},  // Sarajevo International Airport
    {16208, 9188, "SKG", 300, 2},  // Thessaloniki Macedonia International Airport
    {16783, 8649, "SKP", 302, 1},  // Skopje International Airport
    {21081, -3570, "SNN", 303, 1},  // Shannon Airport
    {17079, 9367, "SOF", 304, 1},  // Sofia Airport
    {17416, 6519, "SPU", 305, 1},  // Split Saint Jerome Airport
    {20754, 94, "STN", 306, 1},  // London Stansted Airport
    {19476, 3689, "STR", 307, 1},  // Stuttgart Airport
    {15562, 6498, "SUF", 308, 1},  // Lamezia Terme Sant'Eufemia International Airport
    {23551, 2255, "SVG", 309, 2},  // Stavanger Airport, Sola
    {22391, 14964, "SVO", 311, 1},  // Sheremetyevo International Airport
    {14967, -2357, "SVQ", 312, 1},  // Seville Airport
    {19415, 3051, "SXB", 313, 1},  // Strasbourg Airport
    {19117, 5202, "SZG", 314, 1},  // Salzburg Airport
    {21434, 5961, "SZZ", 315, 1},  // Solidarity Szczecin–Goleniów Airport
    {16668, 17982, "TBS", 316, 1},  // Tbilisi International Airport
    {16944, 7701, "TGD", 317, 1},  // Podgorica Airport / Podgorica Golubovci Airbase
    {16566, 7888, "TIA", 318, 1},  // Tirana International Airport Mother Teresa
    {24206, 8905, "TKU", 319, 1},  // Turku Airport
    {23765, 9933, "TLL", 320, 1},  // Lennart Meri Tallinn Airport
    {14005, -583, "TLM", 321, 1},  // Zenata – Messali El Hadj Airport
    {17452, 546, "TLS", 322, 1},  // Toulouse-Blagnac Airport
    {24566, 9442, "TMP", 323, 1},  // Tampere-Pirkkala Airport
    {14293, -2369, "TNG", 324, 1},  // Tangier Ibn Battuta Airport
    {27873, 7568, "TOS", 325, 1},  // Tromsø Airport
    {25383, 4370, "TRD", 326, 1},  // Trondheim Airport, Værnes
    {23675, 4103, "TRF", 327, 1},  // Sandefjord Airport, Torp
    {18080, 3060, "TRN", 328, 1},  // Turin Airport
    {18331, 5387, "TRS", 329, 1},  // Trieste Airport
    {18259, 4878, "TSF", 330, 1},  // Treviso Airport
    {18324, 8535, "TSR", 331, 1},  // Timișoara Traian Vuia International Airport
    {14238, -2128, "TTU", 332, 1},  // Sania Ramel Airport
    {14740, 4091, "TUN", 333, 2},  // Tunis Carthage International Airport
    {17784, 7489, "TZL", 335, 1},  // Tuzla International Airport
    {19454, 8905, "UDJ", 336, 1},  // Uzhhorod International Airport
    {25517, 8113, "UME", 337, 1},  // Umeå Airport
    {25220, 8705, "VAA", 338, 1},  // Vaasa Airport
    {17293, 11130, "VAR", 339, 1},  // Varna Airport
    {23065, 7338, "VBY", 340, 2},  // Visby Airport
    {18202, 4941, "VCE", 342, 1},  // Venice Marco Polo Airport
    {19244, 6628, "VIE", 343, 2},  // Vienna International Airport
    {22237, 14905, "VKO", 345, 2},  // Vnukovo International Airport
    {15796, -192, "VLC", 347, 1},  // Valencia Airport
    {21854, 10114, "VNO", 348, 1},  // Vilnius International Airport
    {19513, 17736, "VOG", 349, 1},  // Volgograd International Airport
    {18158, 4355, "VRN", 350, 1},  // Verona Villafranca Valerio Catullo Airport
    {23836, 6653, "VST", 351, 1},  // Stockholm Västerås Airport
    {20866, 8387, "WAW", 352, 2},  // Warsaw Chopin Airport
    {20980, 8261, "WMI", 354, 1},  // Warsaw Modlin Airport
    {20441, 6753, "WRO", 355, 1},  // Copernicus Wrocław Airport
    {17639, 6141, "ZAD", 356, 2},  // Zadar Airport
    {18297, 6428, "ZAG", 358, 1},  // Zagreb Franjo Tuđman International Airport
    {16666, -417, "ZAZ", 359, 1},  // Zaragoza Airport
    {22221, 15260, "ZIA", 360, 1},  // Zhukovsky International Airport
    {18983, 3419, "ZRH", 361, 4},  // Zürich Airport
    {18001, 14939, "AAQ", 365, 1},  // Anapa Vityazevo Airport
    {18994, 3824, "ACH", 366, 1},  // Sankt Gallen Altenrhein Airport
    {19882, -886, "ACI", 367, 3},  // Alderney Airport
    {15093, 15388, "ADF", 370, 1},  // Adıyaman Airport
    {22518, 5139, "AGH", 371, 1},  // Ängelholm-Helsingborg Airport
    {16253, 3316, "AHO", 372, 1},  // Alghero-Fertilia Airport
    {16769, 3521, "AJA", 373, 1},  // Ajaccio Napoléon Bonaparte airport
    {15862, 17210, "AJI", 374, 1},  // Ağrı Airport
    {26236, 7713, "AJR", 375, 1},  // Arvidsjaur Airport
    {27990, 9349, "ALF", 376, 1},  // Alta Airport
    {20476, 1785, "ANR", 377, 1},  // Antwerp International Airport (Deurne)
    {27718, 6456, "ANX", 378, 2},  // Andøya Airport, Andenes
    {17447, 5345, "AOI", 380, 1},  // Marche Airport
    {14169, 10858, "AOK", 381, 1},  // Karpathos Airport
    {25840, 16287, "ARH", 382, 1},  // Talagi Airport
    {18470, 8506, "ARW", 383, 1},  // Arad International Airport
    {17957, 969, "AUR", 384, 1},  // Aurillac airport
    {17563, 1961, "AVN", 385, 1},  // Avignon Caumont airport
    {16342, 10383, "AXD", 386, 1},  // Alexandroupoli Democritus Airport
    {15172, 16447, "BAL", 387, 1},  // Batman Airport
    {19063, 9386, "BAY", 388, 1},  // Maramureș International Airport
    {27622, 7416, "BDU", 389, 1},  // Bardufoss Airport
    {22992, -2945, "BEB", 390, 2},  // Benbecula Airport
    {16743, -2683, "BGC", 392, 1},  // Bragança Airport
    {21847, -2349, "BHD", 393, 1},  // George Best Belfast City Airport
    {17387, -609, "BIQ", 394, 1},  // Biarritz Pays Basque airport
    {28240, 11877, "BJF", 395, 1},  // Båtsfjord Airport
    {15557, -2729, "BJZ", 396, 1},  // Badajoz Airport
    {24169, 6206, "BLE", 397, 1},  // Dala Airport
    {23742, 7177, "BMA", 398, 1},  // Stockholm-Bromma Airport
    {26184, 4887, "BNN", 399, 1},  // Brønnøysund Airport, Brønnøy
    {20312, -736, "BOH", 400, 1},  // Bournemouth Airport
    {18765, 3000, "BRN", 401, 2},  // Bern Airport
    {19661, 6678, "BRQ", 403, 1},  // Brno-Tuřany Airport
    {22809, -2977, "BRR", 404, 3},  // Barra Airport
    {18016, 594, "BVE", 407, 1},  // Brive Souillac airport
    {28349, 11614, "BVG", 408, 1},  // Berlevåg Airport
    {17314, 6671, "BWK", 409, 1},  // Brač Airport
    {21239, 7191, "BZG", 410, 1},  // Ignacy Jan Paderewski Bydgoszcz Airport
    {15848, 11170, "BZI", 411, 1},  // Balıkesir Airport
    {21286, 13670, "BZK", 412, 1},  // Bryansk International Airport
    {18584, 4530, "BZO", 413, 1},  // Bolzano Airport
    {17329, 1342, "BZR", 414, 1},  // Béziers Vias airport
    {22175, -2275, "CAL", 415, 1},  // Campbeltown Airport
    {15490, -3742, "CAT", 416, 1},  // Cascais Airport
    {17286, 923, "CCF", 417, 1},  // Carcassonne Salvaza Airport
    {16086, 29, "CDT", 418, 1},  // Castellón-Costa Azahar Airport
    {23709, 15206, "CEE", 419, 1},  // Cherepovets Airport
    {22018, -3336, "CFN", 420, 1},  // Donegal Airport
    {19671, -182, "CFR", 421, 1},  // Caen Carpiquet airport
    {14798, 5844, "CIY", 422, 1},  // Comiso Airport
    {16055, 10571, "CKZ", 423, 1},  // Çanakkale Airport
    {17012, 3517, "CLY", 424, 1},  // Calvi Sainte Catherine Airport
    {18255, 2352, "CMF", 425, 1},  // Chambéry Aix les Bains airport
    {28297, -9060, "CNP", 426, 1},  // Neerlerit Inaat Airport
    {15599, 6832, "CRV", 427, 1},  // Crotone Sant'Anna Pythagoras Airport
    {17819, 3049, "CUF", 428, 1},  // Cuneo International Airport
    {19304, 10392, "CWC", 429, 1},  // Chernivtsi International Airport
    {17423, 916, "DCM", 430, 1},  // Castres Mazamet Airport
    {18908, 2036, "DIJ", 431, 2},  // Dijon Longvic airport
    {15158, 16080, "DIY", 433, 1},  // Diyarbakır Airport
    {18816, 2171, "DLE", 434, 1},  // Dole Tavaux Airport
    {22581, -1210, "DND", 435, 1},  // Dundee Airport
    {19343, 14040, "DNK", 436, 1},  // Dnipro International Airport
    {19435, -832, "DNR", 437, 2},  // Dinard Pleurtuit Saint-Malo airport
    {15114, 11881, "DNZ", 439, 1},  // Çardak Airport
    {19746, 62, "DOL", 440, 1},  // Deauville Normandie airport
    {17343, -716, "EAS", 441, 1},  // San Sebastián Airport
    {17104, 4096, "EBA", 442, 1},  // Marina di Campo Airport
    {22210, 3421, "EBJ", 443, 1},  // Esbjerg Airport
    {15248, 8200, "EFL", 444, 1},  // Kefallinia Airport
    {17930, 207, "EGC", 445, 1},  // Bergerac Dordogne-Périgord airport
    {20258, 14636, "EGO", 446, 1},  // Belgorod International Airport
    {26113, -5761, "EGS", 447, 1},  // Egilsstaðir Airport
    {27345, 9370, "ENF", 448, 1},  // Enontekio Airport
    {23676, -1109, "EOI", 449, 2},  // Eday Airport
    {23368, 9789, "EPU", 451, 1},  // Pärnu Airport
    {15884, 15811, "ERC", 452, 1},  // Erzincan Airport
    {15983, 16468, "ERZ", 453, 1},  // Erzurum International Airport
    {18550, 17732, "ESL", 454, 1},  // Elista Airport
    {19593, 2501, "ETZ", 455, 1},  // Metz-Nancy-Lorraine Airport
    {20294, -1366, "EXT", 456, 1},  // Exeter International Airport
    {15439, 15713, "EZS", 457, 1},  // Elazığ Airport
    {21507, 3464, "FCN", 458, 1},  // Sea-Airport Cuxhaven/Nordholz / Nordholz Naval Airbase
    {17503, 1767, "FNI", 459, 1},  // Nîmes-Arles-Camargue Airport
    {16573, 6214, "FOG", 460, 1},  // Foggia Gino Lisa Airport
    {17678, 4828, "FRL", 461, 1},  // Forlì-Luigi Ridolfi International Airport
    {24633, 2010, "FRO", 462, 1},  // Florø Airport
    {13769, 3529, "GAF", 463, 1},  // Gafsa Ksar International Airport
    {19774, -1041, "GCI", 464, 1},  // Guernsey Airport
    {17833, 15205, "GDZ", 465, 1},  // Gelendzhik Airport
    {14094, 13488, "GEC", 466, 0},  // Lefkoniko Airport / Geçitkale Air Base
    {26853, 8326, "GEV", 466, 1},  // Gällivare Airport
    {21011, 12407, "GME", 467, 1},  // Gomel Airport
    {18145, 2132, "GNB", 468, 1},  // Grenoble Alpes Isère Airport
    {15260, 8570, "GPA", 469, 1},  // Patras Araxos Agamemnon Airport
    {14875, -1511, "GRX", 470, 1},  // F.G.L. Airport Granada-Jaén Airport
    {26618, -7207, "GRY", 471, 1},  // Grímsey Airport
    {21965, 3336, "GWT", 472, 2},  // Westerland Sylt Airport
    {14520, 12919, "GZP", 474, 1},  // Gazipaşa-Alanya Airport
    {22676, 5128, "HAD", 475, 1},  // Halmstad Airport
    {23738, 2083, "HAU", 476, 1},  // Haugesund Airport, Karmøy
    {21551, 5661, "HDF", 477, 1},  // Heringsdorf Airport
    {25718, -6091, "HFN", 478, 1},  // Hornafjörður Airport
    {28272, 9467, "HFT", 479, 1},  // Hammerfest Airport
    {24872, 2430, "HOV", 480, 1},  // Ørsta-Volda Airport, Hovden
    {14544, 14514, "HTY", 481, 1},  // Hatay Airport
    {21430, -140, "HUY", 482, 2},  // Humberside Airport
    {28404, 10393, "HVG", 484, 1},  // Honningsvåg Airport, Valan
    {20855, 6319, "IEG", 485, 1},  // Zielona Góra-Babimost Airport
    {26423, -9254, "IFJ", 486, 1},  // Ísafjörður Airport
    {19554, 9874, "IFO", 487, 1},  // Ivano-Frankivsk International Airport
    {15991, 17551, "IGD", 488, 1},  // Iğdır Airport
    {16691, 214, "ILD", 489, 1},  // Lleida-Alguaire Airport
    {22273, -2503, "ILY", 490, 2},  // Islay Airport
    {23017, -1619, "INV", 492, 2},  // Inverness Airport
    {15879, 8329, "IOA", 494, 1},  // Ioannina King Pyrrhus National Airport
    {15142, 12147, "ISE", 495, 1},  // Süleyman Demirel International Airport
    {22776, 16376, "IWA", 496, 1},  // Ivanovo South Airport
    {19683, -878, "JER", 497, 1},  // Jersey Airport
    {23103, 5627, "JKG", 498, 2},  // Jönköping Airport
    {15337, 10456, "JKH", 500, 1},  // Chios Island National Airport
    {14974, 10139, "JMK", 501, 1},  // Mykonos Island National Airport
    {25064, 11848, "JOE", 502, 2},  // Joensuu Airport
    {14086, 10441, "JSH", 504, 1},  // Sitia Airport
    {15671, 9401, "JSI", 505, 1},  // Skiathos Island National Airport
    {24960, 10271, "JYV", 506, 1},  // Jyväskylä Airport
    {14808, 16477, "KAC", 507, 1},  // Qamishli International Airport
    {25714, 11077, "KAJ", 508, 1},  // Kajaani Airport
    {26395, 11696, "KAO", 509, 1},  // Kuusamo Airport
    {15016, 14781, "KCM", 510, 1},  // Kahramanmaraş Airport
    {23596, 9132, "KDL", 511, 1},  // Kärdla Airport
    {26311, 9833, "KEM", 512, 1},  // Kemi-Tornio Airport
    {18670, 13003, "KHE", 513, 1},  // Kherson International Airport
    {20872, -3810, "KIR", 514, 1},  // Kerry Airport
    {27890, 11957, "KKN", 515, 1},  // Kirkenes Airport, Høybuktmoen
    {22674, 6515, "KLR", 516, 2},  // Kalmar Airport
    {14827, 8810, "KLX", 518, 1},  // Kalamata Airport
    {23119, 16408, "KMW", 519, 1},  // Kostroma Sokerkino Airport
    {23583, -1162, "KOI", 520, 2},  // Kirkwall Airport
    {25488, 9257, "KOK", 522, 2},  // Kokkola-Pietarsaari Airport
    {25219, 7108, "KRF", 524, 1},  // Kramfors-Sollefteå Höga Kusten Airport
    {22519, 3642, "KRP", 525, 3},  // Midtjyllands Airport / Air Base Karup
    {19465, 8496, "KSC", 528, 1},  // Košice International Airport
    {23778, 5335, "KSD", 529, 1},  // Karlstad Airport
    {25245, 3130, "KSU", 530, 1},  // Kristiansund Airport, Kvernberget
    {16225, 17246, "KSY", 531, 1},  // Kars Airport
    {17527, 8235, "KVO", 532, 1},  // Morava Airport
    {19217, 13284, "KWG", 533, 1},  // Kryvyi Rih International Airport
    {16114, 8736, "KZI", 534, 1},  // Kozani National Airport Filippos
    {21522, 4288, "LBC", 535, 1},  // Lübeck Blankensee Airport
    {17321, -3351, "LCG", 536, 1},  // A Coruña Airport
    {20602, 22, "LCY", 537, 1},  // London City Airport
    {17271, -3, "LDE", 538, 1},  // Tarbes-Lourdes-Pyrénées Airport
    {22017, -2864, "LDY", 539, 1},  // City of Derry Airport
    {14738, -948, "LEI", 540, 1},  // Almería Airport
    {17036, -2261, "LEN", 541, 1},  // León Airport
    {16935, 564, "LEU", 542, 1},  // Pirineus - la Seu d'Urgel Airport
    {20255, 2178, "LGG", 543, 1},  // Liège Airport
    {18345, 472, "LIG", 544, 1},  // Limoges Airport
    {28028, 9989, "LKL", 545, 1},  // Lakselv Airport, Banak
    {27261, 5444, "LKN", 546, 1},  // Leknes Airport
    {19179, 81, "LME", 547, 1},  // Le Mans-Arnage Airport
    {14199, 5047, "LMP", 548, 1},  // Lampedusa Airport
    {21081, 15815, "LPK", 549, 1},  // Lipetsk Airport
    {18472, -478, "LRH", 550, 1},  // La Rochelle Île de Ré Airport
    {19104, -1376, "LRT", 551, 2},  // Lorient South Brittany (Bretagne Sud) Airport
    {23952, -518, "LSI", 553, 3},  // Sumburgh Airport
    {14160, 14379, "LTK", 556, 1},  // Latakia International Airport
    {18402, 3564, "LUG", 557, 1},  // Lugano Airport
    {25819, 7486, "LYC", 558, 1},  // Lycksele Airport
    {18592, 6274, "MBX", 559, 1},  // Maribor Edvard Rusjan Airport
    {28412, 11131, "MEH", 560, 1},  // Mehamn Airport
    {19789, 3406, "MHG", 561, 1},  // Mannheim-City Airport
    {24049, 7959, "MHQ", 562, 1},  // Mariehamn Airport
    {14303, 4302, "MIR", 563, 1},  // Monastir Habib Bourguiba International Airport
    {26314, 5286, "MJF", 564, 1},  // Mosjøen Airport, Kjærstad
    {15623, 10639, "MJT", 565, 1},  // Mytilene International Airport
    {14112, -1183, "MLN", 566, 1},  // Melilla Airport
    {15374, 15236, "MLX", 567, 1},  // Malatya Erhaç Airport
    {21804, -572, "MME", 568, 1},  // Teesside International Airport
    {25098, 2905, "MOL", 569, 1},  // Molde Airport, Årø
    {18830, 14980, "MPW", 570, 2},  // Mariupol International Airport
    {14889, 16253, "MQM", 572, 1},  // Mardin Airport
    {26546, 5721, "MQN", 573, 1},  // Mo i Rana Airport, Røssvoll
    {15499, 16664, "MSR", 574, 1},  // Muş Airport
    {21582, 12038, "MVQ", 575, 1},  // Mogilev Airport
    {24383, 5805, "MXX", 576, 1},  // Mora Airport
    {17405, 17455, "NAL", 577, 1},  // Nalchik Airport
    {14430, 4175, "NBE", 578, 1},  // Enfidha - Hammamet International Airport
    {18372, 2439, "NCY", 579, 1},  // Annecy Meythet airport
    {14946, 16823, "NKT", 580, 1},  // Şırnak Şerafettin Elçi Airport
    {16807, 14029, "NOP", 581, 1},  // Sinop Airport
    {20176, -1998, "NQY", 582, 1},  // Cornwall Airport Newquay
    {23435, 6500, "NRK", 583, 2},  // Norrköping Airport
    {18861, -644, "NTE", 585, 1},  // Nantes Atlantique Airport
    {21070, 513, "NWI", 586, 1},  // Norwich Airport
    {15137, -1940, "ODB", 587, 1},  // Córdoba Airport
    {25363, 7596, "OER", 588, 1},  // Örnsköldsvik Airport
    {16387, 15234, "OGU", 589, 1},  // Ordu–Giresun Airport
    {17282, 17843, "OGZ", 590, 1},  // Vladikavkaz Beslan International Airport
    {25480, 3842, "OLA", 591, 1},  // Ørland Airport
    {16603, 12835, "ONQ", 592, 1},  // Zonguldak Çaycuma Airport
    {23689, 6015, "ORB", 593, 1},  // Örebro Airport
    {25277, 5802, "OSD", 594, 1},  // Åre Östersund Airport
    {18185, 7525, "OSI", 595, 1},  // Osijek Airport
    {24754, 13662, "PES", 596, 1},  // Petrozavodsk Airport
    {17096, 1148, "PGF", 597, 2},  // Perpignan-Rivesaltes (Llabanère) Airport
    {18635, 123, "PIS", 599, 1},  // Poitiers-Biard Airport
    {23113, 11358, "PKV", 600, 1},  // Princess Olga Pskov International Airport
    {17931, 4119, "PMF", 601, 1},  // Parma Airport
    {17108, -659, "PNA", 602, 2},  // Pamplona Airport
    {14727, 4788, "PNL", 604, 2},  // Pantelleria Airport
    {24585, 8720, "POR", 606, 2},  // Pori Airport
    {14860, -3434, "PRM", 608, 1},  // Portimão Airport
    {17352, -167, "PUF", 609, 1},  // Pau Pyrénées Airport
    {15570, 8306, "PVK", 610, 1},  // Aktion National Airport
    {14471, 2132, "QSF", 611, 1},  // Ain Arnat Airport
    {16248, 5965, "QSR", 612, 1},  // Salerno Costa d'Amalfi Airport
    {20556, 8486, "RDO", 613, 1},  // Warsaw Radom Airport
    {17763, 993, "RDZ", 614, 1},  // Rodez–Aveyron Airport
    {15228, 6261, "REG", 615, 2},  // Reggio Calabria Airport
    {22234, 4853, "RKE", 617, 2},  // Copenhagen Roskilde Airport
    {25651, -8775, "RKV", 619, 2},  // Reykjavík Domestic Airport
    {21567, 4911, "RLG", 621, 1},  // Rostock-Laage Airport
    {22507, 6106, "RNB", 622, 1},  // Ronneby Airport
    {22025, 5904, "RNN", 623, 1},  // Bornholm Airport
    {19228, -694, "RNS", 624, 2},  // Rennes-Saint-Jacques Airport
    {25031, 4537, "RRS", 626, 1},  // Røros Airport
    {25935, 4458, "RVK", 627, 1},  // Rørvik Airport, Ryum
    {20243, 10457, "RWN", 628, 1},  // Rivne International Airport
    {23242, 15572, "RYB", 629, 1},  // Staroselye Airport
    {19686, 2844, "SCN", 630, 1},  // Saarbrücken Airport
    {25011, 6978, "SDL", 631, 1},  // Sundsvall-Härnösand Airport
    {17371, -1528, "SDR", 632, 1},  // Seve Ballesteros-Santander Airport
    {20628, 277, "SEN", 633, 1},  // London Southend Airport
    {13887, 4276, "SFA", 634, 1},  // Sfax Thyna International Airport
    {25850, 8431, "SFT", 635, 1},  // Skellefteå Airport
    {21986, 3917, "SGD", 636, 1},  // Sønderborg Airport
    {27432, 6013, "SKN", 637, 1},  // Stokmarknes Airport, Skagen
    {19455, 7654, "SLD", 638, 1},  // Sliač Airport
    {16381, -2201, "SLM", 639, 2},  // Salamanca Airport
    {15076, 10765, "SMI", 641, 1},  // Samos Airport
    {18925, -861, "SNR", 642, 1},  // Saint-Nazaire-Montoir Airport
    {18675, 6864, "SOB", 643, 1},  // Hévíz–Balaton Airport
    {27915, 8384, "SOJ", 644, 1},  // Sørkjosen Airport
    {20380, -543, "SOU", 645, 1},  // Southampton Airport
    {23917, 2136, "SRP", 646, 1},  // Stord Airport, Sørstokken
    {26383, 4988, "SSJ", 647, 1},  // Sandnessjøen Airport, Stokka
    {18044, 16845, "STW", 648, 1},  // Stavropol Shpakovskoye Airport
    {17143, 16451, "SUI", 649, 1},  // Vladislav Ardzinba Sukhum International Airport
    {19081, 9154, "SUJ", 650, 1},  // Satu Mare International Airport
    {27297, 5868, "SVJ", 651, 1},  // Svolvær Airport, Helle
    {24777, 11578, "SVL", 652, 1},  // Savonlinna Airport
    {23286, -2532, "SYY", 653, 2},  // Stornoway Airport
    {16502, 14627, "SZF", 655, 1},  // Samsun-Çarşamba Airport
    {21393, 8375, "SZY", 656, 1},  // Olsztyn-Mazury Airport
    {19628, 8097, "TAT", 657, 2},  // Poprad-Tatry Airport
    {23323, 10675, "TAY", 659, 1},  // Tartu Airport
    {14792, 3551, "TBJ", 660, 1},  // Tabarka-Aïn Draham International Airport
    {14173, 3248, "TEE", 661, 1},  // Cheikh Larbi Tébessi Airport
    {16455, 11168, "TEQ", 662, 1},  // Tekirdağ Çorlu Airport
    {18879, 15540, "TGK", 663, 1},  // Taganrog Yuzhny Airport
    {18587, 9765, "TGM", 664, 1},  // Târgu Mureş Transilvania International Airport
    {23327, 4938, "THN", 665, 1},  // Trollhättan-Vänersborg Airport
    {16962, 7489, "TIV", 666, 1},  // Tivat Airport
    {16130, 14556, "TJK", 667, 2},  // Tokat Airport
    {17239, 2458, "TLN", 669, 2},  // Toulon-Hyères Airport
    {15165, 4995, "TPS", 671, 1},  // Vincenzo Florio Airport Trapani-Birgi
    {22600, -2748, "TRE", 672, 3},  // Tiree Airport
    {18973, 291, "TUF", 675, 1},  // Tours Val de Loire Airport
    {24063, 5197, "TYF", 676, 1},  // Torsby Airport
    {16398, 15916, "TZX", 677, 1},  // Trabzon International Airport
    {23292, 9004, "URE", 678, 2},  // Kuressaare Airport
    {20700, 14518, "URS", 680, 1},  // Kursk East Airport
    {15387, 17333, "VAN", 681, 1},  // Van Ferit Melen Airport
    {28142, 12418, "VAW", 682, 1},  // Vardø Airport, Svartnes
    {18172, 4132, "VBS", 683, 1},  // Brescia Gabriele d'Annunzio Airport
    {28026, 11938, "VDS", 684, 1},  // Vadsø Airport
    {16893, -3451, "VGO", 685, 1},  // Vigo Airport
    {25832, 6733, "VHM", 686, 1},  // Vilhelmina South Lapland Airport
    {17153, -1090, "VIT", 687, 1},  // Vitoria Airport
    {16682, -1941, "VLL", 688, 2},  // Valladolid Airport
    {15688, 9118, "VOL", 690, 1},  // Nea Anchialos National Airport
    {20726, 15692, "VOZ", 691, 2},  // Voronezh International Airport
    {26288, -5940, "VPN", 693, 1},  // Vopnafjörður Airport
    {16510, -3088, "VRL", 694, 1},  // Vila Real Airport
    {16290, -3156, "VSE", 695, 1},  // Aerodromo Goncalves Lobato (Viseu Airport)
    {22772, 5891, "VXO", 696, 1},  // Växjö Kronoberg Airport
    {23384, -1237, "WIC", 697, 1},  // Wick John O'Groats Airport
    {19509, 1682, "XCR", 698, 1},  // Chalons Vatry airport
    {14698, -2424, "XRY", 699, 1},  // Jerez Airport
    {16102, 11825, "YEI", 700, 1},  // Bursa Yenişehir Airport
    {15020, 17695, "YKO", 701, 1},  // Hakkari Yüksekova Airport
    {15100, 8354, "ZTH", 702, 1},  // Zakynthos International Airport Dionysios Solomos
};

// Runway strip headings, degrees mod 180, one byte each.
constexpr uint8_t kRunwayHeadings[] = {
    52, 7, 83, 100, 158, 54, 167, 22, 58, 65, 176, 119, 133, 100, 53, 92, 97, 41, 58, 87,
    3, 93, 10, 76, 76, 37, 6, 74, 165, 19, 66, 53, 137, 122, 69, 71, 65, 162, 170, 105,
    121, 148, 163, 97, 117, 80, 104, 55, 87, 117, 170, 46, 107, 44, 78, 114, 52, 88, 67, 87,
    14, 65, 130, 77, 155, 44, 134, 132, 131, 42, 125, 138, 85, 8, 82, 66, 80, 169, 64, 138,
    111, 152, 79, 6, 30, 41, 123, 89, 66, 84, 117, 136, 159, 118, 48, 15, 146, 41, 61, 97,
    157, 53, 0, 107, 59, 54, 31, 88, 98, 36, 178, 90, 118, 100, 70, 163, 60, 32, 48, 59,
    71, 70, 0, 48, 113, 30, 88, 171, 46, 36, 105, 68, 159, 11, 26, 14, 52, 164, 46, 105,
    92, 50, 153, 48, 154, 95, 126, 32, 63, 154, 62, 113, 81, 28, 78, 59, 174, 47, 92, 90,
    159, 14, 104, 66, 148, 133, 145, 106, 113, 78, 34, 53, 35, 95, 166, 90, 85, 157, 81, 55,
    17, 138, 26, 69, 86, 45, 71, 106, 86, 78, 90, 15, 78, 176, 22, 126, 137, 70, 87, 112,
    86, 67, 70, 74, 57, 72, 24, 136, 175, 144, 1, 8, 51, 52, 132, 146, 105, 173, 124, 134,
    122, 138, 30, 83, 170, 58, 117, 45, 65, 78, 79, 92, 99, 83, 162, 60, 130, 75, 156, 18,
    53, 158, 11, 173, 63, 160, 67, 18, 62, 74, 16, 158, 46, 75, 84, 58, 132, 121, 109, 23,
    57, 127, 93, 14, 157, 110, 24, 121, 13, 59, 24, 67, 108, 65, 127, 176, 37, 38, 88, 33,
    69, 70, 5, 144, 128, 88, 46, 54, 56, 37, 80, 91, 60, 64, 91, 166, 150, 163, 10, 117,
    104, 166, 165, 52, 95, 53, 44, 72, 99, 106, 179, 64, 90, 49, 157, 131, 136, 4, 174, 85,
    90, 70, 143, 64, 96, 13, 90, 179, 3, 90, 69, 110, 70, 12, 112, 96, 103, 138, 163, 97,
    21, 101, 42, 116, 164, 12, 57, 116, 22, 64, 46, 8, 115, 152, 82, 116, 42, 136, 47, 120,
    120, 10, 96, 137, 155, 42, 99, 27, 80, 133, 49, 136, 25, 25, 165, 128, 121, 110, 32, 150,
    45, 124, 96, 95, 150, 169, 73, 26, 99, 109, 55, 167, 14, 35, 89, 44, 126, 133, 125, 35,
    75, 140, 160, 94, 70, 110, 150, 115, 62, 35, 82, 2, 172, 10, 94, 106, 164, 97, 57, 42,
    20, 124, 48, 41, 179, 176, 157, 169, 32, 153, 141, 15, 175, 163, 55, 91, 90, 115, 170, 59,
    117, 39, 160, 79, 146, 94, 117, 25, 35, 66, 2, 35, 111, 88, 98, 39, 76, 71, 78, 177,
    156, 117, 71, 48, 88, 14, 118, 112, 90, 3, 90, 160, 58, 142, 77, 6, 134, 100, 168, 46,
    61, 42, 22, 82, 80, 65, 62, 104, 120, 133, 73, 112, 49, 110, 142, 50, 110, 83, 18, 114,
    10, 160, 110, 1, 50, 19, 134, 39, 80, 132, 76, 147, 8, 30, 71, 69, 48, 152, 169, 130,
    87, 140, 11, 112, 172, 34, 90, 134, 13, 26, 72, 64, 133, 6, 143, 72, 31, 93, 20, 73,
    73, 46, 31, 45, 34, 176, 24, 20, 81, 150, 93, 16, 72, 53, 84, 144, 177, 19, 143, 146,
    170, 93, 23, 74, 160, 148, 146, 31, 48, 71, 21, 112, 37, 136, 116, 137, 161, 63, 90, 39,
    110, 54, 122, 91, 115, 28, 90, 29, 122, 102, 102, 154, 0, 12, 115, 111, 23, 128, 148, 32,
    18, 17, 30, 152, 28, 76, 126, 174, 107, 125, 68, 90, 52, 75, 130, 113, 153, 31, 116, 175,
    117, 98, 9, 114, 101, 142, 136, 40, 118, 40, 87, 160, 110, 54, 148, 106, 139, 86, 2, 28,
    74, 94, 73, 165, 154, 19, 145, 25, 76, 123, 13, 9, 126, 60, 174, 134, 19, 70, 94, 88,
    93, 113, 49, 104, 74, 146, 139, 49, 60, 51, 135, 128, 47, 110, 168, 15, 158, 112, 59, 0,
    124, 38, 163, 135, 87, 11, 103, 36, 45, 144, 81, 131, 0, 40, 18, 179, 13, 127, 102, 21,
    74, 110, 163,
};

}  // namespace airportdata
