#!/usr/bin/env python3
"""Builds src/airports.h from OurAirports data.

Fetches the public-domain OurAirports airport and runway tables,
filters to major European airports — every `large_airport`, plus the
`medium_airport`s with an IATA code and scheduled service (revealed
only when zoomed in) — joins each airport to its runway headings, and
emits the result as compact const arrays in a C header the firmware
compiles into flash.

Positions are quantized to the same 1/400 degree fixed point as
geo_data.h; runway headings are stored one byte each (degrees mod
180, the reciprocal implied) so the scope can draw the strips the
design calls for. Airports keep only what renders: position, IATA
code, headings. Names ride along as comments for review.

Run from anywhere; it writes firmware/src/airports.h next to this
script's parent. Downloads are cached in the system temp dir so
re-runs are instant.

  ./make_airports.py [--scale 400]
"""

import argparse
import csv
import io
import os
import sys
import tempfile
import urllib.request

BASE = "https://davidmegginson.github.io/ourairports-data/"

# European bounding box, a bit wider than the geography set (lon
# -15..30 / lat 35..72) so airports keep appearing across the whole
# continent as flights range over Europe — Iceland to the Aegean.
LON_MIN, LON_MAX = -25.0, 45.0
LAT_MIN, LAT_MAX = 34.0, 72.0

# Two headings within this many degrees (mod 180) are one strip:
# parallel runways (09L/09R/09C) collapse into a single drawn line.
HEADING_TOLERANCE = 10.0
MAX_HEADINGS = 4


def fetch(filename, cache_dir):
    path = os.path.join(cache_dir, filename)
    if not os.path.exists(path):
        url = BASE + filename
        print(f"fetching {url}")
        with urllib.request.urlopen(url) as response:
            data = response.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def runway_headings(rows):
    """Maps airport ident -> deduplicated runway headings (deg mod 180).

    Prefers the surveyed true heading; falls back to the runway number
    (09L -> 90). Closed runways are skipped.
    """
    headings = {}
    for row in rows:
        if row.get("closed") == "1":
            continue
        heading = None
        try:
            heading = float(row["le_heading_degT"]) % 180.0
        except (KeyError, ValueError):
            ident = row.get("le_ident", "")
            digits = "".join(c for c in ident if c.isdigit())
            if digits:
                heading = (int(digits) * 10) % 180.0
        if heading is None:
            continue
        merged = headings.setdefault(row["airport_ident"], [])
        for existing in merged:
            delta = abs(existing - heading)
            if min(delta, 180.0 - delta) <= HEADING_TOLERANCE:
                break
        else:
            if len(merged) < MAX_HEADINGS:
                merged.append(round(heading))
    return headings


def select_airports(rows):
    """Returns (large, medium) lists of in-box airports worth drawing."""
    large, medium = [], []
    skipped = 0
    for row in rows:
        try:
            lat, lon = float(row["latitude_deg"]), float(row["longitude_deg"])
        except ValueError:
            continue
        if not (LON_MIN <= lon <= LON_MAX and LAT_MIN <= lat <= LAT_MAX):
            continue
        kind = row["type"]
        iata = row.get("iata_code", "").strip()
        if kind == "large_airport":
            if len(iata) != 3:
                skipped += 1  # No IATA code to label with; vanishingly rare.
                continue
            large.append((iata, row["name"], lat, lon, row["ident"]))
        elif kind == "medium_airport":
            # Medium fields only earn a spot with an IATA code and
            # scheduled service — that keeps out the aero clubs and
            # military strips that would bury the scope when zoomed in.
            if len(iata) != 3 or row.get("scheduled_service") != "yes":
                continue
            medium.append((iata, row["name"], lat, lon, row["ident"]))
    if skipped:
        print(f"skipped {skipped} large airport(s) without an IATA code")
    large.sort()
    medium.sort()
    return large, medium


def emit(path, large, medium, headings, scale):
    airports = large + medium
    strips = []  # Flat heading array; airports index into it.
    lines = []
    for iata, name, lat, lon, ident in airports:
        start = len(strips)
        mine = headings.get(ident, [])
        strips.extend(mine)
        lines.append(f'    {{{round(lat * scale)}, {round(lon * scale)}, '
                     f'"{iata}", {start}, {len(mine)}}},  // {name}\n')

    with open(path, "w", encoding="utf-8") as f:
        f.write(f"""\
// Generated by tools/make_airports.py — do not edit by hand.
//
// Major European airports from OurAirports (public domain): every
// large_airport, then the medium_airports with an IATA code and
// scheduled service, within lon {LON_MIN:g}..{LON_MAX:g} / \
lat {LAT_MIN:g}..{LAT_MAX:g},
// positions quantized to 1/{scale:g} degree fixed point. Runway
// headings (degrees mod 180, parallels merged) index into one flat
// byte array. The arrays are const, so they live in flash
// (memory-mapped on the ESP32-S3), not RAM.

#pragma once

#include <stdint.h>

namespace airportdata {{

// Degrees per fixed-point unit: lat = kAirports[i].lat * kDegPerUnit.
constexpr float kDegPerUnit = {1.0 / scale!r}f;

struct Airport {{
  int16_t lat;        // Fixed-point 1/{scale:g} degree.
  int16_t lon;
  char iata[4];       // IATA code, NUL terminated.
  uint16_t rwyStart;  // First entry in kRunwayHeadings.
  uint8_t rwyCount;   // Number of runway strips.
}};

// Large airports first (always drawn), then medium (zoomed in only).
constexpr int kLargeCount = {len(large)};
constexpr int kCount = {len(airports)};

constexpr Airport kAirports[] = {{
""")
        f.writelines(lines)
        f.write("};\n\n")
        f.write("// Runway strip headings, degrees mod 180, one byte each.\n")
        f.write("constexpr uint8_t kRunwayHeadings[] = {\n")
        text = [str(h) for h in strips]
        for i in range(0, len(text), 20):
            f.write("    " + ", ".join(text[i:i + 20]) + ",\n")
        f.write("};\n\n}  // namespace airportdata\n")
    return len(strips)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", type=float, default=400.0,
                        help="fixed-point units per degree")
    args = parser.parse_args()

    cache_dir = os.path.join(tempfile.gettempdir(), "ourairports-cache")
    os.makedirs(cache_dir, exist_ok=True)

    airports = fetch("airports.csv", cache_dir)
    headings = runway_headings(fetch("runways.csv", cache_dir))
    large, medium = select_airports(airports)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "src", "airports.h")
    strip_count = emit(out_path, large, medium, headings, args.scale)

    # sizeof(Airport) is 12 with alignment padding.
    flash = (len(large) + len(medium)) * 12 + strip_count
    print(f"large:  {len(large)} airports")
    print(f"medium: {len(medium)} airports (zoom-revealed)")
    print(f"strips: {strip_count} runway headings")
    print(f"total:  ~{flash / 1024:.1f} KB flash -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
